using UnityEngine;

public class TimeChallengeZone1 : MonoBehaviour
{
    private GameManager2 gameManager;

    void Start()
    {
        gameManager = FindAnyObjectByType<GameManager2>();
        
        if (gameManager == null)
        {
            Debug.LogError("TimeChallengeZone: GameManager2 n√£o encontrado!");
            enabled = false;
        }
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.CompareTag("Player"))
        {
            if (gameManager != null)
            {
                gameManager.SetTimerActive(true); 
                gameManager.ShowWarningText(2.5f);
            }
        }
    }

    private void OnTriggerExit2D(Collider2D other)
    {
        if (other.CompareTag("Player"))
        {
            if (gameManager != null)
            {
                gameManager.SetTimerActive(false);
            }
        }
    }
}